stages:
  - test
  - docker_build
  - make test
  - make lint

test:
  image: "python:2.7"
  stage: test
  script:
    - PYTHONPATH=. py.test --verbose -s

docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
    - make docker_build
